--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Sergittos/ChatCooldown
build-by-default: true
branches:
- main
projects:
  ChatCooldown:
    path: ""
    icon: icon.png
    libs:
      - src: andresbytes/EasyUI/libEasyUI
        version: 1.0.0
...
