main: sergittos\chatcooldown\ChatCooldown
name: ChatCooldown
api: 4.0.0
version: 1.0.2
author: Sergittos (@Sergittos)
website: https://github.com/Sergittos

permissions:
  chatcooldown.admin:
    default: op
  chatcooldown.bypass:
    default: op