## Players will have to wait this amount of seconds before being able to chat again
cooldown: 3

## The message that will be appear when the amount the seconds that have to wait the player have not passed
## Use (time) to put the amount of seconds that have to wait the player to chat again
cooldown-message: "You must wait (time) seconds to chat again!"